"""PDF / CSV report generation for violations."""
from __future__ import annotations

from datetime import datetime
from io import BytesIO, StringIO
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, HRFlowable
)


def build_violation_ticket_pdf(violation: dict, org: str = "SafeCityAI Traffic Enforcement") -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm)
    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "T", parent=styles["Heading1"], fontSize=18, textColor=colors.HexColor("#0f172a"), alignment=TA_CENTER, spaceAfter=4
    )
    sub = ParagraphStyle(
        "S", parent=styles["Normal"], fontSize=10, textColor=colors.HexColor("#64748b"), alignment=TA_CENTER, spaceAfter=12
    )
    body = ParagraphStyle("B", parent=styles["Normal"], fontSize=10, textColor=colors.HexColor("#1e293b"), leading=14)
    label = ParagraphStyle("L", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#64748b"))

    story = []
    story.append(Paragraph("SafeCityAI", title))
    story.append(Paragraph(f"{org} — E-Challan / Violation Notice", sub))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#4f46e5")))
    story.append(Spacer(1, 10))

    ticket = violation.get("ticket_id", "—")
    story.append(Paragraph(f"<b>Ticket ID:</b> {ticket}", body))
    story.append(Paragraph(f"<b>Issued:</b> {violation.get('created_at', datetime.utcnow().isoformat())}", body))
    story.append(Spacer(1, 8))

    data = [
        ["Field", "Details"],
        ["Violation", violation.get("label") or violation.get("violation_type", "—")],
        ["Severity", str(violation.get("severity", "—")).upper()],
        ["Confidence", f"{float(violation.get('confidence', 0)) * 100:.1f}%"],
        ["Vehicle", violation.get("vehicle_class", "—")],
        ["Plate", violation.get("plate_text") or "Not captured"],
        ["Camera", violation.get("camera_id", "—")],
        ["Location", violation.get("location", "—")],
        ["Status", str(violation.get("status", "open")).upper()],
        ["Fine (INR)", f"₹ {float(violation.get('fine_amount', 0)):.2f}"],
        ["Notes", violation.get("notes") or "—"],
    ]
    table = Table(data, colWidths=[45 * mm, 120 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4f46e5")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BACKGROUND", (0, 1), (0, -1), colors.HexColor("#f1f5f9")),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 16))
    story.append(Paragraph(
        "This notice was auto-generated by SafeCityAI object-detection pipeline (YOLO). "
        "Helmet/seatbelt classes benefit from custom-trained weights; current flags combine "
        "COCO detections with enforcement heuristics. Review before final challan issuance.",
        label,
    ))
    story.append(Spacer(1, 20))
    story.append(Paragraph("Authorized by SafeCityAI Control Room", body))
    story.append(Paragraph(datetime.utcnow().strftime("Generated UTC %Y-%m-%d %H:%M"), label))
    doc.build(story)
    return buf.getvalue()


def violations_to_csv(rows: list[dict]) -> str:
    import csv
    buf = StringIO()
    fields = [
        "ticket_id", "violation_type", "severity", "confidence", "location",
        "camera_id", "vehicle_class", "plate_text", "status", "fine_amount",
        "created_at", "notes",
    ]
    w = csv.DictWriter(buf, fieldnames=fields, extrasaction="ignore")
    w.writeheader()
    for r in rows:
        row = dict(r)
        if hasattr(row.get("created_at"), "isoformat"):
            row["created_at"] = row["created_at"].isoformat()
        w.writerow(row)
    return buf.getvalue()
